### PR TITLE
build action loop from git

### PR DESCRIPTION
**Pull request by sciabarracom**

### CODE REVIEW

**Comment by sciabarracom** [comment]
there is an error in building the tests can someone suggest from where I can take an updated testkit?

**Comment by rabbah** [comment]
I'm taking a look but I don't think the akka compatibility is the issue. Did the 2.5 tests pass before?

**Comment by sciabarracom** [comment]
Actually tests were running properly before. The actionloop was merged with all the tests running.

-- 
 Michele Sciabarra
 michele@sciabarra.com



----- Original message -----

**Comment by rabbah** [comment]
@sciabarracom I fixed the 2.5 issues which had to do with stdout not being flushed early enough. I do not know what's going with 2.6 (it doesn't look like it starts up correctly).

**Comment by rabbah** [comment]
here's the error on startup:
```
docker run -p 8080:8080 actionloop-ruby-v2.6
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

**Comment by sciabarracom** [comment]
Will check - 2.6 is my stuff

-- 
 Michele Sciabarra
 michele@sciabarra.com



----- Original message -----

**Comment by dgrove-oss** [comment]
I pulled the flushes in to #41.   I think the rest of this PR is superseded by other PRs

**Pull request closed without merging**
